version: '3'
services:
  api:
    build: ./api
    labels:
      - "traefik.enabled=true"
      - "traefik.backend=api"
      - "traefik.rule=Host:api.pecu.cc"
      - "traefik.port=80"
    networks:
      - "traefik_default"
    restart: always
  front:
    build: ./front
    labels:
      - "traefik.enabled=true"
      - "traefik.backend=front"
      - "traefik.rule=Host:pecu.cc"
      - "traefik.port=80"
    networks:
      - "traefik_default"
    restart: always

networks:
  traefik_default:
    external:
      name: traefik_default
